### ISSUE TITLE
 Call to undefined method STS\HubSpot\Api\Builder::after()"

### ISSUE THREAD

**Issue by onmigregor** [stechstudio/laravel-hubspot#20]
hi Good Day

Is Simple when I  use Contact::take(20)->after(50)->get()

But 
when I use   Contact::take(20)->after(50)->get();;

It give me 

message: "Call to undefined method STS\HubSpot\Api\Builder::after()",…}
exception
: 
"BadMethodCallException"
file
: 
"C:\\xampp\\htdocs\\balabamba\\vendor\\stechstudio\\laravel-hubspot\\src\\Api\\Builder.php"
line
: 
407
message
: 
"Call to undefined method STS\\HubSpot\\Api\\Builder::after()"
trace
: 
[{file: "C:\xampp\htdocs\balabamba\app\Http\HubSpot\ApiHubSpot.php", line: 67, function

**Comment by AdamRollinson** [comment]
Hi, you will need to use [skip](https://github.com/stechstudio/laravel-hubspot/blob/main/src/Api/Builder.php#L250)

**Comment by jszobody** [comment]
Hi @onmigregor , @AdamRollinson is correct. This appears to be an oversight, I intended to have `after()` as an alias of `skip()` so that either could be used, but it doesn't look like that method is in the builder. 

If anyone wants to submit a quick PR for that I'd merge it. Otherwise for now use `skip()`.

**Comment by onmigregor** [comment]
Ok thk Yes, I chekk 5 minutes after my post jeje, 100% work with skip Thanks
